def createGraph(sequence, k):
    kmers = []
    pairs = {}
    for i in range(0,len(sequence)-k):
        kmers.append(sequence[i:i+k])
    for kmer in kmers:
        prefix = kmer[:k-1]
        suffix = kmer[1:]
        if prefix not in pairs.keys():
            pairs[prefix] = suffix
        else:
            pairs[prefix] += ',' + suffix
    
    with open('debrujin_output.txt', 'w') as f:
        for key in pairs.keys():
            f.write(key + ' -> ' + pairs[key] + '\n')
string = "AAGGGGAGCCTCTCGGAACTTACGTGCGCTTGTCGTACAAGGAGTCACAAGACGCGATCGCTCAAATCCTACCCTTTCCAAGACCGGGGCGAGCCCGAGGCGGGTGGTACATATGTGCATAATTACGACGAGACGTTAGGCTGGCAGTCAATACTCAAACGCAGGGGCGCTTAATTTATGGGTCTTCTGTGTACCGCGGCCGAGTCGCAACCATCCATTGAAGCAGCGCGTTCCTGACGCCCCCACCGCGTTCCAACCATTCTCTGGAGGCGATAACCTAGTTGGTAGTTATTAGCTAAGCCGTGAAGAAATGCAAGCTGTTGGTCCATGATTACCGAAAACAATAATTAGCAGGAGACTTTACGGGTACCCTTAAGTGTAGATTCGGCAGAAGACAAGCTGCCGGGCTTAGACAAAAGCCCACCACGGGACTGGAATGCGAGGAAACTCTCGTCTCATGTAGCGGTACGGACGCAGCTGGGTACTCCAGCAACCCTGAGGGGGTTTTGACTCGATTATGCACCATAACCGAACTACTACCATCTGTGAAACGCAGAAAACTTACTAAACTTAGGTGACCTTGGCAAGGCTTAGTAACTCCGAACTGGCCTTGCTTGACCATTATTAACCTGTATTCCGCCTAGGGCCGGCCACCCAGGCTCACTTTCGTAGGACCCCCTCTCTATCTGGCCATAATCCACACTTAATGCACATTAGCGCAAGTGGATCAGAGAACTTAACCATAATACGCATCAGTAAGGTATAACGCCCAGGTTCCGTTGCCCGCGTACCTCCCAAGCGCGACCAATCCGACGATTACGATACTAGACGGGTTCCTATCTTTGGACCCGAGGTTATCGTCTCAAGTGATGCCGTAGCGTATAAACCATATTGTTTGCTCGGAGGCTCCCTCGGACTCTATGTTTACACCGCAGGCGAGCAGTGTTATTAAGCGGGGGAAGCAGAATAAGATTTAACCACGTCCGTTTCGCCTTGTAACTAATAAATGACAAACACTTCAGCCTCTCTCGTCCGGCCTGCTCGTGGGGGATACTGGCGGGTTCTTACAGGATGAGTACGCTACATGTTTGCTATGGGAGATGTAGACCCATGCTCCTCCATACGGTCTCATCTGGACTAAAGTCTGGTGCATAAACCTCCAGCAAACATTTCAGCCGGCTAGCATAAGGATCAGAAGTAGGTTCTAAGGACATGTGGGGACGGGAAGGTCTAGGGTGGCAATATTTCTGTACAGTATCGCAAACCCACACTCGACACCAGCTGCGTCCCTTGTTATAATTAACATGGGGTTATGGGGTCCTTGAAATCAAGCCGGGAAGTATCGATGATGAAGCTATGTATGTAGGAAGCTTGTCGGGGAGTCGTCGATTGGAGACCGCAGACCTGCTGTAGGTAGAGAGGCAATTCTTATAGTGGGAGAAGTTACGGACAACTTTCCCGAGCACCAGGGGCTGACGGCCTTACACGACCCTCTAAGCTGATAGGGGAGTGCAGCTACCGGGTCCCCATCAATGTATACTAGGATATCATCCCCATACTGTTAGCAGAACGACACGCGCGTGTTTAATACAGCGACAGCATGCTGCGGTACACATCTCGTGACCCGTGGCACAATCAGCCTTAACTGAAATTTAATTGCCTTTGGGAAAACTCTTCCCCTAAGGCAGACCGTAAATTATAGGTAAGGAAGTAAAGGCTGCGTTTTAGGGGCAAGAATTGTTAATCCGTAGAACCTCTGTGACGACCAGTGGCATTTCATAATTGAGCTATACCGTGCATGGTCTGAAGCGCTGCATCGACGGCTTTTGCTAACTACTACCAGCTTTCAATAACATTGGACGATTCTCAATACGCCGATTGGTAAGCTAAGTCGGGCTATATATCGGGGACCCCTGTCAGTATTGCGACGAATACTGCGCACTCGAATCGTTATACTGGATTACCAAACCATGATCGACGTCTAGAGTCTGATATGCAGT"
kmer = 12
createGraph(string,kmer)