def sum_protein_string(input, mass_table):
    mass = 0
    for letter in input:
        mass += float(mass_table[letter])
    return mass

mass_dict = {}
with open('./input/mass_table.tsv', 'r') as f:
    file_lines = f.read().split('\n')

for line in file_lines:
    mass_dict[line.split(',')[0]] = line.split(',')[1]

print sum_protein_string("MTRQTDGGSSHHGIQVWCLMAHMLCYLGVCHSAFATQKKTQNTHPDQWATMAAAILPKYDKQCQWIHEQPFIAIDVHCNYDCPNEMWDRNVVPPHDRHMKNIRPNETKTVQVKMKALLQKHVFGKDCPMSFVQGTDYMFMIVFILADKGDVMIWIRFSGIGMSANTVLRVKQGDWCFMMWFDTFALLCPMRLRNVQIFANIPQEMKQFPPIYPSKTHCLRPCVGTCPTWWYWPQAAMQNVKHDCEPLEFQDPDWTSMAYDAQFCRAQCTVVGTIVCKSKYKGISQMDLDFFFEPRSFIPSHTFLKMTHQEHHTHCQTHIRIDSKHKHQHHGAHSTNPRTNRWHKMLFDLMPWYWKDSNNIDGEQWFMWNGINQEWRVDNEVNNNTMDMCMCDTCRDWSHSEYLWKLQHRWETDRLPHCWIWPSKSWDSFQVYVEDPYFMNGQICEDLAVSQRHSGGLNELMPSHKIDHWQGQDQFPEFGKNSSWMNDVTFFRFFIGHTGRSWSHEVWPPGRMEEYADAGNLQVRYFVLNFFSVHCNEAGSSDCPQCIHHQQQFERFTASGDEETTDTGTPQKTMYDNVYRNYDWQQDWSDVWYLPTAGFWHPERNAIEYMGQQFHGNNELVKMTWPLFKHPDLPDDDVHWYACWKEYVSCPRIRWNQHWYYTKFSPQFDTDEHSQSGCHMLNMDDVEWLSETAFPLHKGVVIIDQALVWSTNQPVENFHLETCRADEEADFVACCNIRKHKGNIAPVTWNAVWRGFFICARQMIKCYCYDMYFSNKLLCTYVSYGTWHMIGIKAFNYDYSVPAGIWEEFWPQCHNKQKYMDQYIRIFHYIKWSQYIKIEKASSCIMLIRARERREPRYAAITRHSGQNHHHACLCFWFKIFHIHICIQ", mass_dict)